### ISSUE TITLE
P1188 Library utilities for <=>

### ISSUE THREAD

**Issue by jensmaurer** [jensmaurer/papers#143]
[P1188R0](https://wg21.link/p1188r0) Library utilities for &lt;=&gt; (Barry Revzin)

https://issues.isocpp.org/show_bug.cgi?id=525

**Comment by tituswinters** [comment]
Change the name from compare_3way_type_t to compare_3way_result_t.
SF F N A SA
7  7 1 0 0

Clean up all spellings of 3way to three_way / ThreeWay.
SF F N A SA
2  6 6 1 0

Do the above, come back with a revision that also replaces compare_3way with the comparison object that invokes <=> and introduces compare_three_way_fallback.
SF F N A SA
3  8 2 0 0

Threeway is one word.
SF F N A SA
0  3 6 5 2

In light of not wanting the assume_ functions in P0891, we continue to want compare_three_way_fallback.
SF F N A SA
1  3 5 1 1

We want a fallback/bridging mechanism, we want it to obey the strong_order customization point family, we tentatively like the ordering being provided via template parameter.
SF F  N A SA
1  12 0 0 0

(The fallback/bridging API probably goes into a revision of P0891).

**Comment by tituswinters** [comment]
Non-member, hidden friend, or member.

Make them hidden friends.
Unanimous consent

Extension form for partial-ordered strings.

char_traits specialization: member alias vs. static member function.
Prefer member alias.
SF F N A SA
2  5 4 0 1

General approval per design form (unique_ptr, optional, string, vector)-like.

Approve the design direction for smart pointers.
Unanimous consent

Approve the design direction for optional/variant/stack/queue/reverse_iterator (types that wrap an underlying but make no assumptions about the semantics of underlying comparison operators).
Unanimous consent

Approve the design direction for vector and other lexicographically-ordered types.
Unanimous consent

Approve the design direction for basic_string.
Unanimous consent

Approve the design direction for removal of operator!=, and operator==’s that are unnecessary because of P1185.
Unanimous consent

Add the explicit defaulting for the relevant types (pair, array) - NOT tuple.
SF F N A SA
3  6 1 0 0

Forward to LWG for C++20.
SF F N A SA
9  2 0 0 0

**Comment by tituswinters** [comment]
(There's a possible mix-up between numbers: I'm seeing this listed as both P1188 and P1189 in various places.)

**Comment by jensmaurer** [comment]
Integrated into [P1614](https://wg21.link/p1614) The Mothership Has Landed: Adding <=> to the Library #391.
