### ISSUE TITLE
P0407 Allocator-aware basic_stringbuf

### ISSUE THREAD

**Issue by jensmaurer** [jensmaurer/papers#260]
[P0407R2](https://wg21.link/p0407r2) Allocator-aware basic_stringbuf </td> (Peter Sommerlad)

https://issues.isocpp.org/show_bug.cgi?id=234

Titus Winters 2018-03-28 16:20:00 UTC
Discussed in http://wiki.edg.com/bin/view/Wg21jacksonville2018/P0407

Forward to LWG for C++20?
Unanimous consent

**Comment by PeterSommerlad** [comment]
This paper is included in P0408R6 because it touches the same classes and also same member functions

**Comment by mclow** [comment]
This is actually back in LEWG.

**Comment by PeterSommerlad** [comment]
Slight correction, p0407 is integrated into p0408. Both in principle and in isolation were blessed by LEWG, but the combination required changed API, that has not been seen, but would have come up anyway, because both papers touch the same classes. P0407 thus no longer need to be reviewed by lwg, but p0408 is, after LEWG blesses the API where features overlapped.

**Comment by jensmaurer** [comment]
Continued in P0408 Efficient Access to basic_stringbuf's Buffer #100.
